package:
  name: pyf3d
  version: '1.0.0'

source:
  git_url: https://github.com/holdymoldy/pyF3D.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyopencl
    - futures # [py2k]

about:
  summary: 'Python wrapper for F3D filtering.'
